Vagrant.configure("2") do |config|
	config.vm.define :elk do |elk|
		  elk.vm.box = "ubuntu/precise64"
		  elk.vm.hostname ="elk"

		     elk.vm.network "forwarded_port", guest: 80, host: 8080
			 elk.vm.network "private_network", ip: "192.168.27.130"
			# elk.vm.network "public_network", type: "dhcp", bridge: "eth0"
			elk.vm.provider "virtualbox" do |vb|
				# Display the VirtualBox GUI when booting the machine
				#vb.gui = true
				# Customize the amount of memory on the VM:
				vb.memory = "2048"
			end
		   
		   elk.vm.provision "shell", inline: <<-SHELL
			sudo apt-get update 
			wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.tar.gz
			tar -zxvf elasticsearch-5.5.0.tar.gz
			cd elasticsearch-5.5.0
			
			sudo add-apt-repository ppa:openjdk-r/ppa
			sudo apt-get update
			sudo apt-get install openjdk-8-jdk
			bin/elasticsearch


		   SHELL
	end
	
	
	
	
		config.vm.define :syslogger do |syslogger|
		  syslogger.vm.box = "ubuntu/precise64"
		  syslogger.vm.hostname ="syslogger"

		    # syslogger.vm.network "forwarded_port", guest: 80, host: 1000
			 syslogger.vm.network "private_network", ip: "192.168.27.132"
			# syslogger.vm.network "public_network", type: "dhcp", bridge: "eth0"
			syslogger.vm.provider "virtualbox" do |vb|
				# Display the VirtualBox GUI when booting the machine
				#vb.gui = true
				# Customize the amount of memory on the VM:
				vb.memory = "1024"
			end
		   

	end
	
end
