
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
   config.vm.define "ansible_server" do |ansible_server|
		ansible_server.vm.box = "centos/7"
		  ansible_server.vm.hostname = "ansibleserver"
	ansible_server.vm.network "private_network", ip: "192.168.100.200"
		ansible_server.vm.network "public_network"
		   ansible_server.vm.provider "virtualbox" do |vb|
				vb.memory = "1024"
			end
  end
  
     config.vm.define "ansible_node" do |ansible_node|
		ansible_node.vm.box = "ubuntu/trusty64"
		ansible_node.vm.hostname = "ansiblenode"
	ansible_node.vm.network "private_network", ip: "192.168.100.210"
		ansible_node.vm.network "public_network"
		ansible_node.vm.provider "virtualbox" do |vb|
				vb.memory = "1024"
			end
  end


end
