
Vagrant.configure("2") do |devstack|
  devstack.vm.box = "ubuntu/xenial64"
  devstack.vm.hostname = "devstack"
	
  devstack.vm.boot_timeout=5
   devstack.vm.network "private_network", type: "dhcp"
   devstack.vm.network "private_network", ip: "192.168.27.100"
	 devstack.vm.provider "virtualbox" do |vb|
	  vb.memory = "3072"
	end
end
